server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
            client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: device-service-get
          uri: http://${DEVICE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/device
            - Method=GET
          filters:
            - SetPath=/api/device/all

        - id: house-service-get
          uri: http://${HOUSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/api/house
            - Method=GET
          filters:
            - SetPath=/api/house/all

        - id: message-service-get
          uri: http://${MESSAGE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/message
            - Method=GET
          filters:
            - SetPath=/api/message/all

        - id: message-service-post
          uri: http://${MESSAGE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/api/message
            - Method=POST
          filters:
            - SetPath=/api/message

        - id: device-service-post
          uri: http://${DEVICE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/device
            - Method=POST
          filters:
            - SetPath=/api/device

        - id: house-service-post
          uri: http://${HOUSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path:/api/house
            - Method=POST
          filters:
            - SetPath=/api/house

        - id: device-service-put
          uri: http://${DEVICE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/device/{id}
            - Method=PUT
          filters:
            - SetPath=/api/device/{id}

        - id: device-service-delete
          uri: http://${DEVICE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/api/device/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/device/{id}
